version: '3'

services:

  # AS #
  AS-router:
    image: router
    volumes:
      - ./data/AS-router:/data
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: AS-router
    networks:
      AS:
        ipv4_address: 120.0.32.5
      interco:
        ipv4_address: 120.0.38.2

  AS-dmz-router:
    image: router
    volumes:
      - ./data/AS-dmz-router:/data
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: AS-dmz-router
    networks:
      AS-DMZ:
        ipv4_address: 120.0.34.2
      AS:
        ipv4_address: 120.0.32.2

  AS-dns:
    image: dns-server
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: AS-dns
    volumes:
      - ./data/AS-dns:/data
    networks:
      AS-DMZ:
        ipv4_address: 120.0.34.3
  
  interco-routeur:
    image: router
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: interco-routeur
    volumes:
      - ./data/interco-routeur:/data
    networks:
      interco:
        ipv4_address: 120.0.38.3
      zone:
        ipv4_address: 130.0.0.3


  # Partie Entreprise de l'AS #
  acces-entreprise-router:
    image: router
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: acces-entreprise-router
    volumes:
      - ./data/acces-entreprise-router:/data
    networks:
      acces-entreprise:
        ipv4_address: 120.0.36.2
      AS:
        ipv4_address: 120.0.32.3
  
  entreprise-box:
    image: box-entreprise
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: entreprise-box
    volumes:
      - ./data/entreprise-box:/data
    networks:
      entreprise:
        ipv4_address: 10.128.0.2
      acces-entreprise:
        ipv4_address: 120.0.36.3

  entreprise-dns:
    image: dns-server
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: entreprise-dns
    volumes:
      - ./data/entreprise-dns:/data
    networks:
      entreprise-dmz:
        ipv4_address: 
          10.0.0.3

  # Service de site web sur le port 80
  web:
    environment:
      HTTPD_ROOT: /usr/local/apache2/htdocs/
    cap_add:
      - NET_ADMIN
      - ALL
    image: web
    ports:
      - 80:80
    volumes:
      - ./data/web-entreprise:/data
      - ./Website:/usr/local/apache2/htdocs/
    networks:
       entreprise-dmz: 
        ipv4_address: 10.0.0.5

  entreprise-client:
    image: client-entreprise
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: entreprise-client
    dns: 10.0.0.3
    volumes:
      - ./data/entreprise-client:/data
    networks:
      entreprise:
          ipv4_address: 10.128.0.4

  entreprise-dmz-router:
    image: router
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: entreprise-dmz-router
    volumes:
      - ./data/entreprise-dmz-router:/data
    privileged: true
    networks:
      entreprise-dmz:
        ipv4_address: 10.0.0.2
      entreprise:
        ipv4_address: 10.128.0.3


  # Partie Client de l'AS #
  acces-client-router:
    image: router
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: acces-client-router
    volumes:
      - ./data/acces-client-router:/data
    networks:
      acces-client:
        ipv4_address: 120.0.40.2
      AS:
        ipv4_address: 120.0.32.4

  client-box:
    image: box
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: client-box
    volumes:
      - ./data/client-box:/data
    networks:
      client:
        ipv4_address: 192.168.0.2
      acces-client:
        ipv4_address: 120.0.40.3

  client-machine:
    image: client
    cap_add:
      - NET_ADMIN
      - ALL
    container_name: client-machine
    dns: 120.0.34.3
    volumes:
      - ./data/client-machine:/data
    networks:
      client:
        ipv4_address: 192.168.0.3

  # Service VoIP

#  tele:
#    image: mlan/asterisk
#    networks:
#      entreprise-dmz: 
#        ipv4_address: 10.0.0.4
#    cap_add:
#      - sys_ptrace                          
#      - net_admin                           
#      - net_raw                            
#    ports:
#      - "${SMS_PORT-8080}:${WEBSMSD_PORT:-80}" 
#      - "5060:5060/udp"                     
#      - "5060:5060"                         
#      - "5061:5061"                        
#      - "10000-10099:10000-10099/udp"      
#    environment:
#      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}     
#      - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
#      - PULSE_SERVER=unix:/run/pulse/socket 
#      - PULSE_COOKIE=/run/pulse/cookie      
#      - WEBSMSD_PORT=${WEBSMSD_PORT-80}     
#    volumes:
#      - tele-conf:/srv                      
#      - Dockerfiles/voip/pulse:/run/pulse:rshared          
  #    - /etc/localtime:/etc/localtime:ro    

#volumes:
#  tele-conf: 


networks:
  AS:
    ipam:
      config:
        - subnet: 120.0.32.0/23

  AS-DMZ:
    ipam:
      config:
        - subnet: 120.0.34.0/23

  acces-entreprise:
    ipam:
      config:
        - subnet: 120.0.36.0/23
  
  acces-client:
    ipam:
      config:
        - subnet: 120.0.40.0/21

  client:
    ipam:
      config:
        - subnet: 192.168.0.0/24

  entreprise:
    ipam:
      config:
        - subnet: 10.128.0.0/9
  
  entreprise-dmz:
    ipam:
      config:
        - subnet: 10.0.0.0/9

  interco:
    ipam:
      config:
        - subnet: 120.0.38.0/23
      
  zone:
    ipam:
      config:
        - subnet: 130.0.0.0/24